In [1]:
#1 create a Numpy array 'arr' of integers from 0 tp 5 and print its datatype.
import numpy as np
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int32


In [30]:
#2 Given a NumpPy array 'arr' , check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype == np.float64:
    print("The data type of 'arr' is float64.")
else:
    print("The data type of 'arr' is not float64.")

The data type of 'arr' is float64.


In [7]:
#3 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1 + 2j, 3 - 4j, 5 + 6j])
if arr.dtype == np.complex128:
    print("The data type of 'arr' is complex128.")
else:
    print("The data type of 'arr' is not complex128.")

The data type of 'arr' is complex128.


In [19]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([0,1,2,3,4,5])
arr = arr.astype(np.float32())
print(arr.dtype)

float32


In [20]:
#5 Given a Numpy array 'arr' with flaot64 data type,convert it to flaot32 to reduce decimal precision.
arr = np.array([0,1,2,3,4,5])
arr = arr.astype(np.float32())
print(arr.dtype)

float32


In [24]:
#6. write a function array_attributes that takes a NumPy array as intput array as input and return its shape,size and data type.
def array_attributes(input_array):
    shape = input_array.shape
    size = input_array.size
    dtype = input_array.dtype
    return shape,size,dtype
arr = np.array([[1,2,3],[4,5,6]])
shape,size,dtype = array_attributes(arr)
print("shape : ",shape)
print("size : ",size)
print("shape : ",dtype)

shape :  (2, 3)
size :  6
shape :  int32


In [29]:
#7. create a function array_dimension that takes a NumPy array as input and return its dimensionality.
def array_dimension(input_array):
    return input_array.ndim
arr = np.array([[[1,2,3],[4,5,6]]])
dimensionality = array_dimension(arr)
print("dimensionality : ",dimensionality)

dimensionality :  3


In [34]:
#8 Design a function item_size_into that takes a Numpy array as input and returns the item size and the total size in bytes.
def item_size_into(input_array):
    item_size = input_array.itemsize
    total_size = input_array.size * item_size
    return item_size,total_size
arr = np.array([[1,2,3],[4,5,6]])
item_size,total_size = item_size_into(arr)
print("Item size : ",item_size)
print("total size : ",total_size)

Item size :  4
total size :  24


In [35]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array. 
def array_strides(input_array):
    return input_array.strides
arr = np.array([[1,2,3],[4,5,6]])
strides = array_strides(arr)
print(strides)

(12, 4)


In [38]:
#10. Design a function shape_stide_relationship thar takes a NumPy array as input and returns the shape and strides of the array.
def shape_stide_relationship(input_array):
    shape = input_array.shape
    strides = input_array.strides
    return shape, strides
arr = np.array([[1,2,3],[4,5,6]])
shape,strides = shape_stide_relationship(arr)
print("shape : ",shape)
print("strides : ",strides)

shape :  (2, 3)
strides :  (12, 4)


In [41]:
#11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
    return np.zeros(n)
n = int(input("enter number : "))
zeros_arr = create_zeros_array(n)
print(zeros_arr)

enter number : 8
[0. 0. 0. 0. 0. 0. 0. 0.]


In [42]:
#12. write a function `create_ones_matrix` that takes integers `row` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x col`.
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows,cols)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
#13 write a function `generate_range_array` that takes three integers start,stop and step as arguments and create a NumPy array with a range starting from `start`,ending at stop(exclusive), and with the specified 'step'.
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
start = 1
stop = 10
step = 2
range_array = generate_range_array(start,stop,step)
print(range_array)

[1 3 5 7 9]


In [45]:
#14 Design a function `generate_linear_space` that takes two floats `start`,`stop`,and an integer `num` as arguments and generates and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive).
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)

[0.   0.25 0.5  0.75 1.  ]


In [46]:
#15. Create a function `create_identify_matrix` that takes an interger `n` as input and generates a square identify matrix of size `n x n` using `numpy.eye`.
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)
n = 3
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
#16. write a function that takes a Python list and converts is into a NumPy array.
def list_to_numpy_array(input_list):
    return np.array(input_list)
my_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(my_list)
print(numpy_array)

[1 2 3 4 5]


In [48]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_array = original_array.view()
view_array[0, 0] = 100
print("Original Array:")
print(original_array)
print("\nView Array:")
print(view_array)


Original Array:
[[100   2   3]
 [  4   5   6]]

View Array:
[[100   2   3]
 [  4   5   6]]


In [49]:
#18. write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
result = concatenate_arrays(array1, array2, axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [51]:
#19. create two NumPy arrays with different shapes and concatenate them horizontally using `numpy` concatenate.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])
result = np.concatenate((array1, array2), axis=1)
print(result)

[[1 2 5]
 [3 4 6]]


In [52]:
#20. write a function that vertically stacks multiple NumPy arrays given as a list.
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
array3 = np.array([[7, 8], [9, 10]])
stacked_array = stack_arrays_vertically([array1, array2, array3])
print(stacked_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [53]:
#21. write a function using NumPy to create an array of integers within a specified range(inclusive) with a given step size.
def create_integer_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)
start = 1
stop = 10
step = 2
integer_range_array = create_integer_range_array(start, stop, step)
print(integer_range_array)


[1 3 5 7 9]


In [54]:
#22. write a Python function using NumPy to generate an array of 10 equally spaced values  between 0 and 1(inclusive)
def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)
equally_spaced_values = generate_equally_spaced_values()
print(equally_spaced_values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [55]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000(inclusive).
def generate_logarithmically_spaced_values():
    return np.logspace(0, 3, 5)
logarithmically_spaced_values = generate_logarithmically_spaced_values()
print(logarithmically_spaced_values)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [56]:
#24. Write a Python function using NumPy to create an array thar contains 5 rows and 3 columns, where the values are eandom integers between 1 and 100.
def generate_random_array():
    return np.random.randint(1, 101, size=(5, 3))
random_array = generate_random_array()
print(random_array)

[[ 48  58   7]
 [ 99  62  99]
 [ 87  10   5]
 [ 11  46  98]
 [ 60  48 100]]


In [27]:
#25. write a function that takes a Pandas DataFrame and replace all negative values in a specific column with zeros. Use Numpy Operations within the Pandas DataFrame.

In [59]:
#26. Access the 3rd element from the given NumPy array.
arr=np.array([10,20,30,40,50])
third_element = arr[2]
print(third_element)

30


In [60]:
#27 Retrieve the element at index(1,2) from the 2D Numpy array.
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
element_at_index_1_2 = arr_2d[1, 2]
print("Element at index (1, 2):", element_at_index_1_2)

Element at index (1, 2): 6


In [62]:
#28. Using boolean indexing,extract elements greater than 5 from the given Numpy array.
arr = np.array([3,8,2,10,5,7])
result = arr[arr>5]
print("Elements greater than 5:", result)

Elements greater than 5: [ 8 10  7]


In [63]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1,2,3,4,5,6,7,8,9])
result = arr[2:6]
print("Sliced elements:", result)

Sliced elements: [3 4 5 6]


In [64]:
#30 Slice the 2D Numpy array to extract the sub-array `[[2,3],[5,6]]` from the given array.
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]
print("Sub-array [[2,3],[5,6]]:")
print(sub_array)


Sub-array [[2,3],[5,6]]:
[[2 3]
 [5 6]]


In [65]:
#31. Write a NumPy function to extract elements in specific order from given 2D array based on indices provided in another array.
def extract_elements_by_indices(arr_2d, indices):
    
    flattened_arr = arr_2d.flatten()
    extracted_elements = flattened_arr[indices]
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([4, 1, 6, 0, 2, 8])
extracted_elements = extract_elements_by_indices(arr_2d, indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [5 2 7 1 3 9]


In [66]:
#32. Create a NumPy function that filters elements greter than a threshoild from a given 1D array using boolean indexing.
def filter_elements_greater_than_threshold(arr, threshold):
    filtered_array = arr[arr > threshold]
    return filtered_array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5
filtered_elements = filter_elements_greater_than_threshold(arr, threshold)
print("Filtered elements greater than", threshold, ":", filtered_elements)

Filtered elements greater than 5 : [6 7 8 9]


In [67]:
#33. Develop a NumPy function that extract specific elements from a 3D array using indices provided in three separate array for each dimension.
def extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    extracted_elements = arr_3d[indices_dim1, indices_dim2, indices_dim3]
    return extracted_elements

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

indices_dim1 = np.array([0, 1])  
indices_dim2 = np.array([1, 2]) 
indices_dim3 = np.array([0, 2]) 

extracted_elements = extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements:")
print(extracted_elements)


Extracted elements:
[ 4 18]


In [68]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using Boolean indexing.
def filter_elements_by_conditions(arr, condition1, condition2):
    
    combined_condition = np.logical_and(condition1, condition2)
    filtered_elements = arr[combined_condition]
    return filtered_elements

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = arr > 3
condition2 = arr % 2 == 0

filtered_elements = filter_elements_by_conditions(arr, condition1, condition2)
print("Filtered elements:", filtered_elements)

Filtered elements: [4 6 8]


In [73]:
#35. Create a NumPy function that extracts elements from a 2D array using row and columns indices provided in separate arrays.
import numpy as np

def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    extracted_elements = arr_2d[row_indices, col_indices]
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])  
col_indices = np.array([1, 0, 2])  

extracted_elements = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)
print("Extracted elements:")
print(extracted_elements)


In [69]:
#36. Given an array arr of shape(3,3) add scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result = arr + 5
print("Result after adding scalar value of 5 to each element:")
print(result)


Result after adding scalar value of 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [142]:
#37. Consider two arrays arr1 of shape(1,3) and arr2 of shape(3,4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# Transpose arr1 to match the shape of arr2 for broadcasting
arr1_broadcasted = arr1.T  # Transpose arr1 to make it of shape (3, 1)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr1_broadcasted * arr2

print("arr1:")
print(arr1)

print("\narr2:")
print(arr2)

print("\nResult:")
print(result)



arr1:
[[2 3 4]]

arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [143]:
#38. Given a 1D array arr1 of shape(1,4) and a 2D array arr2 of shape(4,3) and arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np

# Create arr1 of shape (1, 4) and arr2 of shape (4, 3)
arr1 = np.array([[2, 3, 4, 5]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

# Reshape arr1 to match the shape of arr2 for broadcasting
arr1_broadcasted = arr1.reshape(4, 1)

# Add arr1 to each row of arr2 using broadcasting
result = arr1_broadcasted + arr2

print("arr1:")
print(arr1)

print("\narr2:")
print(arr2)

print("\nResult:")
print(result)


arr1:
[[2 3 4 5]]

arr2:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result:
[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]
 [15 16 17]]


In [75]:
#40. Given array arr1 of shape(2,3) and arr2 of shape(2,2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[1, 2],
                 [3, 4]])

arr2_reshaped = arr2[:, :, np.newaxis]

# Perform multiplication using broadcasting
result = arr1 * arr2_reshaped

print("Result after broadcasting multiplication:")
print(result)


Result after broadcasting multiplication:
[[[ 1  2  3]
  [ 8 10 12]]

 [[ 3  6  9]
  [16 20 24]]]


In [76]:
#41. Calculate column-wise mean for the given array:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
column_means = np.mean(arr, axis=0)
print("Column-wise mean:", column_means)

Column-wise mean: [2.5 3.5 4.5]


In [77]:
#42 find maximum value in each row of the given array:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

max_values_per_row = np.max(arr, axis=1)
print("Maximum value in each row:", max_values_per_row)


Maximum value in each row: [3 6]


In [78]:
#43. for the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
max_indices_per_column = np.argmax(arr, axis=0)
print("Indices of maximum value in each column:", max_indices_per_column)


Indices of maximum value in each column: [1 1 1]


In [79]:
#44.for the given array, apply custom function to calculate moving sum along rows.
def moving_sum(row):
    return np.cumsum(row)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

moving_sum_array = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Moving sum along rows:")
print(moving_sum_array)


Moving sum along rows:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [80]:
#45. in the given array, check if all elements in each column are even.
def check_even(column):
    return np.all(column % 2 == 0)

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

all_even_columns = np.apply_along_axis(check_even, axis=0, arr=arr)
print("Check if all elements in each column are even:", all_even_columns)


Check if all elements in each column are even: [False False False]


In [81]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
def reshape_array(original_array, m, n):
    reshaped_matrix = np.reshape(original_array, (m, n))
    return reshaped_matrix

original_array = np.array([1, 2, 3, 4, 5, 6])

m = 2
n = 3
reshaped_matrix = reshape_array(original_array, m, n)

print("Reshaped matrix:")
print(reshaped_matrix)


Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [82]:
#47. Create a function that takes a matric as input and returns the flattened array.
def flatten_matrix(input_matrix):
    flattened_array = input_matrix.flatten()
    return flattened_array

input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)

print("Flattened array:")
print(flattened_array)


Flattened array:
[1 2 3 4 5 6]


In [83]:
#48. write a function that concatenates two given arrays along a specified axis.

def concatenate_arrays(array1, array2, axis):
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])
axis = 1

concatenated_array = concatenate_arrays(array1, array2, axis)
print("Concatenated array:")
print(concatenated_array)

Concatenated array:
[[1 2 5 6]
 [3 4 7 8]]


In [84]:
#49. create a function that splits an array into multiple sub-array along a specified axis.
def split_array(original_array, num_splits, axis):
    split_arrays = np.split(original_array, num_splits, axis=axis)
    return split_arrays
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
num_splits = 3
axis = 0
split_arrays = split_array(original_array, num_splits, axis)
print("Sub-arrays after splitting:")
for arr in split_arrays:
    print(arr)

Sub-arrays after splitting:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [144]:
#50. write a function that inserts and then deletes elements from a given array at specified indices.

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    
    for idx, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, value)

    original_array = np.delete(original_array, indices_to_delete)

    return original_array

# Test the function
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified Array:", modified_array)


Modified Array: [ 1 10 11  4  5]


In [88]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. perfom element-wise addition between `arr1` and `arr2`.
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 10, size=(5, 5))  # Example: 5x5 array of random integers from 1 to 100

# Create arr2 with integers from 1 to 10
arr2= np.random.randint(1, 10, size=(5, 5))

# Perform element-wise addition between arr1 and arr2
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)


arr1:
[[5 4 8 2 1]
 [2 2 9 7 6]
 [8 4 1 8 3]
 [6 3 5 2 2]
 [5 2 2 9 9]]

arr2:
[[4 7 1 4 6]
 [1 1 6 3 3]
 [1 4 6 5 6]
 [8 1 4 6 2]
 [8 5 4 1 7]]

Result of element-wise addition:
[[ 9 11  9  6  7]
 [ 3  3 15 10  9]
 [ 9  8  7 13  9]
 [14  4  9  8  4]
 [13  7  6 10 16]]


In [94]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)


arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [102]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` integers from 1 to 5. perform element-wise multiplication between `arr1` by `arr2`.
arr1 = np.random.randint(1, 5, size=(3, 3))
arr2 = np.random.randint(1, 5, size=(3, 3))
result = arr1 * arr2
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)


arr1:
[[4 4 3]
 [2 4 3]
 [1 2 4]]

arr2:
[[3 1 4]
 [3 4 3]
 [2 4 2]]

Result of element-wise multiplication:
[[12  4 12]
 [ 6 16  9]
 [ 2  8  8]]


In [103]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)


arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [104]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = np.power(arr1, arr2)
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise exponentiation:")
print(result)


arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [105]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring_occurrences(arr, substring):
    return sum(s.count(substring) for s in arr)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print("Occurrences of '{}' within the array: {}".format(substring, occurrences))

Occurrences of 'hello' within the array: 3


In [106]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
def extract_uppercase_characters(arr):
    return [char for s in arr for char in s if char.isupper()]
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase_characters(arr)
print("Uppercase characters extracted from the array:", uppercase_characters)

Uppercase characters extracted from the array: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [108]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def replace_substring(arr, substring, new_string):
    return np.array([s.replace(substring, new_string) for s in arr])
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
substring = 'apple'
new_string = 'orange'
arr_with_replacement = replace_substring(arr, substring, new_string)

print("Array with replaced substrings:")
print(arr_with_replacement)

Array with replaced substrings:
['orange' 'banana' 'grape' 'pineorange']


In [109]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
def concatenate_strings_elementwise(arr1, arr2):
    return np.array([s1 + s2 for s1, s2 in zip(arr1, arr2)])
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_array = concatenate_strings_elementwise(arr1, arr2)

print("Concatenated array:")
print(concatenated_array)


Concatenated array:
['HelloOpen' 'WorldAI']


In [110]:
#60. Write a function that finds the length of the longest string in a NumPy array.
def longest_string_length(arr):
    return max(map(len, arr))
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string_length(arr)
print("Length of the longest string:", longest_length)

Length of the longest string: 9


In [111]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions
dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Mean: 510.68
Median: 494.0
Variance: 97438.4576
Standard Deviation: 312.151337655311


In [113]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
dataset = np.random.randint(1, 101, size=50)
percentile_25th = np.percentile(dataset, 25)
percentile_75th = np.percentile(dataset, 75)
print("25th Percentile:", percentile_25th)
print("75th Percentile:", percentile_75th)

25th Percentile: 29.25
75th Percentile: 78.5


In [115]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]
print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: -0.9999999999999999


In [116]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [117]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
data = np.random.randint(10, 1001, size=50)
percentiles = np.percentile(data, [10, 50, 90])
quartiles = np.percentile(data, [25, 75])
print("10th Percentile:", percentiles[0])
print("Median (50th Percentile):", percentiles[1])
print("90th Percentile:", percentiles[2])
print("First Quartile (25th Percentile):", quartiles[0])
print("Third Quartile (75th Percentile):", quartiles[1])


10th Percentile: 149.9
Median (50th Percentile): 579.5
90th Percentile: 860.5000000000001
First Quartile (25th Percentile): 335.25
Third Quartile (75th Percentile): 692.25


In [118]:
#66. Create a NumPy array of integers and find the index of a specific element.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
index = np.where(arr == 5)[0]
print("Index of the element 5:", index)

Index of the element 5: [4]


In [119]:
#67. Generate a random NumPy array and sort it in ascending order.
random_array = np.random.randint(1, 100, size=10)
sorted_array = np.sort(random_array)
print("Random array:", random_array)
print("Sorted array in ascending order:", sorted_array)


Random array: [41 95 94 99 70 33  5 83 99 91]
Sorted array in ascending order: [ 5 33 41 70 83 91 94 95 99 99]


In [120]:
#68. Filter elements >20  in the given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_elements = arr[arr > 20]

print("Filtered elements greater than 20:", filtered_elements)


Filtered elements greater than 20: [25 42 30]


In [121]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
filtered_elements = arr[arr % 3 == 0]

print("Filtered elements divisible by 3:", filtered_elements)


Filtered elements divisible by 3: [12 15]


In [122]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

print("Filtered elements ≥ 20 and ≤ 40:", filtered_elements)


Filtered elements ≥ 20 and ≤ 40: [20 30 40]


In [123]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)


Byte order: =


In [124]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print("Byte-swapped array:", arr)

Byte-swapped array: [16777216 33554432 50331648]


In [125]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)


Original array: [1 2 3]
Swapped byte order array: [16777216 33554432 50331648]


In [146]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check system endianness
system_endianness = np.dtype('<i4').newbyteorder()

# Swap the byte order based on system endianness
swapped_arr = arr.newbyteorder(system_endianness)

print("Original array:", arr)
print("Swapped byte order array based on system endianness:", swapped_arr)

Byte swapping is not necessary for the current system.


In [ ]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
byte_swapping_needed = arr.dtype.byteorder != '='
if byte_swapping_needed:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")

In [129]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)

Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [130]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 999
print("Original matrix:")
print(matrix)
print("Modified view_slice:")
print(view_slice)

Original matrix:
[[999  36   2]
 [  2  14   9]
 [ 64  31  81]]
Modified view_slice:
[[999  36]
 [  2  14]]


In [132]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print(array_a)
print("Modified view_b:")
print(view_b)

[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
Modified view_b:
[[ 6  7]
 [ 9 10]]


In [133]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
print("Original orig_array:")
print(orig_array)
print("Modified reshaped_view:")
print(reshaped_view)

Original orig_array:
[[99  2  3  4]
 [ 5  6  7  8]]
Modified reshaped_view:
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [134]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data = np.random.randint(0, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 10
print("Original data:")
print(data)

print("\nCopy of data with elements greater than 5:")
print(data_copy)
print("\nDoes modifying data_copy affect the original data?")
print(np.array_equal(data, data_copy))


Original data:
[[5 6 2 6]
 [7 7 5 6]
 [2 7 3 3]]

Copy of data with elements greater than 5:
[10  6  7  7  6  7]

Does modifying data_copy affect the original data?
False


In [135]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition Result:")
print(addition_result)

print("\nSubtraction Result:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction Result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [136]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])
multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nMatrix Multiplication Result:")
print(multiplication_result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication Result:
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [138]:
#83. Create a matrix `E` and find its transpose.
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
E_transpose = np.transpose(E)
print("Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [139]:
#84. Generate a square matrix `F` and compute its determinant.
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)

print("\nDeterminant of Matrix F:", determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F: -9.51619735392994e-16


In [140]:
#85. Create a square matrix `G` and find its inverse.
G = np.array([[1, 2],
              [3, 4]])

inverse_G = np.linalg.inv(G)

print("Matrix G:")
print(G)

print("\nInverse of Matrix G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of Matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
